# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'BrickDesigner.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(520, 371)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(20, 330, 471, 31))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.NoButton)
        self.buttonBox.setCenterButtons(False)
        self.buttonBox.setProperty("additionalButton", True)
        self.buttonBox.setObjectName("buttonBox")
        self.box_bricks = QtWidgets.QComboBox(Dialog)
        self.box_bricks.setGeometry(QtCore.QRect(150, 80, 161, 31))
        self.box_bricks.setObjectName("box_bricks")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(20, 80, 141, 31))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(20, 120, 141, 31))
        self.label_2.setObjectName("label_2")
        self.box_size = QtWidgets.QSpinBox(Dialog)
        self.box_size.setGeometry(QtCore.QRect(150, 120, 81, 31))
        self.box_size.setMinimum(1)
        self.box_size.setMaximum(3)
        self.box_size.setProperty("value", 1)
        self.box_size.setObjectName("box_size")
        self.text_content = QtWidgets.QPlainTextEdit(Dialog)
        self.text_content.setGeometry(QtCore.QRect(20, 230, 471, 91))
        self.text_content.setObjectName("text_content")
        self.box_scale = QtWidgets.QDoubleSpinBox(Dialog)
        self.box_scale.setGeometry(QtCore.QRect(150, 160, 81, 31))
        self.box_scale.setDecimals(1)
        self.box_scale.setSingleStep(0.5)
        self.box_scale.setProperty("value", 100.0)
        self.box_scale.setObjectName("box_scale")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(20, 160, 141, 31))
        self.label_3.setObjectName("label_3")
        self.check_svg = QtWidgets.QCheckBox(Dialog)
        self.check_svg.setGeometry(QtCore.QRect(390, 140, 84, 20))
        self.check_svg.setChecked(True)
        self.check_svg.setObjectName("check_svg")
        self.check_png = QtWidgets.QCheckBox(Dialog)
        self.check_png.setGeometry(QtCore.QRect(390, 110, 84, 20))
        self.check_png.setObjectName("check_png")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(320, 110, 61, 21))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(20, 200, 141, 31))
        self.label_5.setObjectName("label_5")
        self.check_preview = QtWidgets.QCheckBox(Dialog)
        self.check_preview.setGeometry(QtCore.QRect(130, 200, 121, 31))
        self.check_preview.setChecked(False)
        self.check_preview.setObjectName("check_preview")
        self.pushButton_2 = QtWidgets.QPushButton(Dialog)
        self.pushButton_2.setGeometry(QtCore.QRect(20, 30, 181, 31))
        self.pushButton_2.setObjectName("pushButton_2")
        self.check_json = QtWidgets.QCheckBox(Dialog)
        self.check_json.setGeometry(QtCore.QRect(390, 170, 84, 20))
        self.check_json.setChecked(True)
        self.check_json.setObjectName("check_json")
        self.pushButton_3 = QtWidgets.QPushButton(Dialog)
        self.pushButton_3.setGeometry(QtCore.QRect(330, 80, 161, 31))
        self.pushButton_3.setObjectName("pushButton_3")
        self.check_translator = QtWidgets.QCheckBox(Dialog)
        self.check_translator.setGeometry(QtCore.QRect(320, 200, 141, 31))
        self.check_translator.setChecked(False)
        self.check_translator.setObjectName("check_translator")
        self.text_path = QtWidgets.QLineEdit(Dialog)
        self.text_path.setGeometry(QtCore.QRect(220, 30, 271, 31))
        self.text_path.setObjectName("text_path")

        self.retranslateUi(Dialog)
        self.buttonBox.helpRequested.connect(Dialog.help) # type: ignore
        self.buttonBox.clicked['QAbstractButton*'].connect(Dialog.buttonPressed) # type: ignore
        self.box_bricks.currentIndexChanged['QString'].connect(Dialog.brickChanged) # type: ignore
        self.box_size.valueChanged['int'].connect(Dialog.sizeChanged) # type: ignore
        self.box_scale.valueChanged['double'].connect(Dialog.scaleChanged) # type: ignore
        self.check_preview.toggled['bool'].connect(Dialog.preview) # type: ignore
        self.pushButton_2.released.connect(Dialog.changeExportFolder) # type: ignore
        self.text_content.textChanged.connect(Dialog.contentChanged) # type: ignore
        self.pushButton_3.released.connect(Dialog.loadFromJSON) # type: ignore
        self.check_translator.toggled['bool'].connect(Dialog.showTranslator) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.box_bricks, self.box_size)
        Dialog.setTabOrder(self.box_size, self.box_scale)
        Dialog.setTabOrder(self.box_scale, self.text_content)
        Dialog.setTabOrder(self.text_content, self.buttonBox)
        Dialog.setTabOrder(self.buttonBox, self.check_png)
        Dialog.setTabOrder(self.check_png, self.check_svg)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Available Bricks"))
        self.label_2.setText(_translate("Dialog", "Available Sizes"))
        self.box_scale.setSuffix(_translate("Dialog", "%"))
        self.label_3.setText(_translate("Dialog", "Content Scale"))
        self.check_svg.setText(_translate("Dialog", "SVG"))
        self.check_png.setText(_translate("Dialog", "PNG"))
        self.label_4.setText(_translate("Dialog", "Save as:"))
        self.label_5.setText(_translate("Dialog", "Content"))
        self.check_preview.setText(_translate("Dialog", "Toggle preview"))
        self.pushButton_2.setToolTip(_translate("Dialog", "Change directory for brick export"))
        self.pushButton_2.setText(_translate("Dialog", "Select export folder ..."))
        self.check_json.setText(_translate("Dialog", "JSON"))
        self.pushButton_3.setToolTip(_translate("Dialog", "Change directory for brick export"))
        self.pushButton_3.setText(_translate("Dialog", "Load from JSON .."))
        self.check_translator.setText(_translate("Dialog", "Toggle Translator"))
