# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'translation.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(517, 545)
        self.tableWidget = QtWidgets.QTableWidget(Dialog)
        self.tableWidget.setGeometry(QtCore.QRect(10, 90, 491, 441))
        self.tableWidget.setRowCount(0)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(2)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(10, 50, 141, 31))
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(10, 10, 181, 31))
        self.pushButton.setObjectName("pushButton")
        self.text_path = QtWidgets.QLineEdit(Dialog)
        self.text_path.setGeometry(QtCore.QRect(210, 10, 291, 31))
        self.text_path.setObjectName("text_path")
        self.text_language = QtWidgets.QLineEdit(Dialog)
        self.text_language.setGeometry(QtCore.QRect(160, 50, 291, 31))
        self.text_language.setObjectName("text_language")

        self.retranslateUi(Dialog)
        self.pushButton.released.connect(Dialog.getTranslationFolder) # type: ignore
        self.tableWidget.cellChanged['int','int'].connect(Dialog.contentChanged) # type: ignore
        self.tableWidget.cellClicked['int','int'].connect(Dialog.contentSelected) # type: ignore
        self.text_language.textChanged['QString'].connect(Dialog.exportLanguageChanged) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "Original"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "Translated"))
        self.label.setText(_translate("Dialog", "Translation Language"))
        self.pushButton.setText(_translate("Dialog", "Select translation folder .."))
        self.text_language.setText(_translate("Dialog", "default"))
