# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tutorial_creator.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(482, 520)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(280, 20, 191, 421))
        self.buttonBox.setOrientation(QtCore.Qt.Vertical)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.NoButton)
        self.buttonBox.setObjectName("buttonBox")
        self.checkBox = QtWidgets.QCheckBox(Dialog)
        self.checkBox.setGeometry(QtCore.QRect(290, 470, 85, 21))
        self.checkBox.setChecked(True)
        self.checkBox.setObjectName("checkBox")
        self.checkBox_2 = QtWidgets.QCheckBox(Dialog)
        self.checkBox_2.setGeometry(QtCore.QRect(290, 450, 85, 21))
        self.checkBox_2.setChecked(True)
        self.checkBox_2.setObjectName("checkBox_2")
        self.tutorial_list = QtWidgets.QListWidget(Dialog)
        self.tutorial_list.setGeometry(QtCore.QRect(10, 40, 261, 461))
        self.tutorial_list.setDragEnabled(True)
        self.tutorial_list.setDragDropOverwriteMode(True)
        self.tutorial_list.setDragDropMode(QtWidgets.QAbstractItemView.InternalMove)
        self.tutorial_list.setDefaultDropAction(QtCore.Qt.MoveAction)
        self.tutorial_list.setObjectName("tutorial_list")
        self.lineEdit = QtWidgets.QLineEdit(Dialog)
        self.lineEdit.setGeometry(QtCore.QRect(10, 20, 261, 23))
        self.lineEdit.setObjectName("lineEdit")

        self.retranslateUi(Dialog)
        self.checkBox.toggled['bool'].connect(Dialog.toggleCreator) # type: ignore
        self.checkBox_2.toggled['bool'].connect(Dialog.togglePreview) # type: ignore
        self.buttonBox.clicked['QAbstractButton*'].connect(Dialog.buttonPressed) # type: ignore
        self.tutorial_list.itemChanged['QListWidgetItem*'].connect(Dialog.update) # type: ignore
        self.tutorial_list.indexesMoved['QModelIndexList'].connect(Dialog.update) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.checkBox.setText(_translate("Dialog", "Creator"))
        self.checkBox_2.setText(_translate("Dialog", "Preview"))
        self.lineEdit.setText(_translate("Dialog", "TutorialName"))
