name: auto-format
on: push
jobs:
  format:
    # Check if the PR is not from a fork
    runs-on: ubuntu-latest
    steps:
      - name: black
        uses: lgeiger/black-action@v1.0.1
        with:
          args: .
      - name: Check for modified files
        id: git-check
        run: echo "modified=$(if git diff-index --quiet HEAD --; then echo "false"; else echo "true"; fi)" >> $GITHUB_OUTPUT
        
        if: steps.git-check.outputs.modified == 'true'
      - name: Check out changes            
      - uses: actions/checkout@v3
      - name: Push changes
        run: |
          git config --global user.name 'StofflR'
          git config --global user.email 'StofflR@users.noreply.github.com'
          git commit -am "Automated report"
          git push
